FROM jenkins/inbound-agent:4.14-1
USER root
RUN apt-get update && apt-get install -y openssl curl
# Install Witness
RUN curl -L https://github.com/testifysec/witness/releases/download/v0.3.0/witness-v0.3.0-linux-amd64.tar.gz | tar -xz -C /usr/local/bin
USER jenkins
